### ISSUE TITLE
Rote Box vollständig umranden

### ISSUE THREAD

**Issue by apfelpfluecker** [polygnomnom/wikibook-vcp-mde#3]
Ich fände es auffälliger, wenn die Warn-Boxen vollständig rot umrandet würden.
Geht um:
`::: {.warnung}
Textwarnung
:::`

**Comment by polygnomnom** [comment]
Die Überlegung kann ich verstehen, allerdings finde ich sie aus designtechnischen Gründen nicht sondernlich appealing. Alternativer Vorschlag: Statt den Hintergrund grau-transparent zu hinterlegen, wird er vcp-rot-transparent hinterlegt, `rgba(240,83,93,0.3)`, so wie in diesem Beispiel:
![grafik](https://github.com/polygnomnom/wikibook-vcp-mde/assets/113123199/7bb7e1ff-c508-46af-8f46-d3beb1a1d641)

**Comment by apfelpfluecker** [comment]
Finde ich gut. Mir geht es vor allem, um eine eindeutige Sichtbarkeit: Achtung, hier muss ich was unbedingt lesen. Die wäre durch den Vorschlag gegeben.

**Comment by polygnomnom** [comment]
Gut, habe ich nun so implementiert:)
